### PR TITLE
Fixed the getJSON request failed! error

### PR DESCRIPTION
**Pull request by makemeafirewall**
https://github.com/neilh10/thingspeakmultichannel-highcharts/issues/2

The fix was from https://forum.arduino.cc/index.php?topic=213058.msg4211691#msg4211691

### CODE REVIEW

**Comment by VastSky** [comment]
> #2
> 
> The fix was from https://forum.arduino.cc/index.php?topic=213058.msg4211691#msg4211691

Fabulous! Thanks for fixing this!!

**Comment by neilh10** [comment]
Thanks very much. I've not tested yet, but if anybody else tests it let me know.

**Comment by makemeafirewall** [comment]
I tested it by saving the file to disk and opening it in the browser, it shows it's been raining at your area since November 14th 😁
chart

**Comment by neilh10** [comment]
Very nice. Motivated my to test it as well - nice to have it back working.  
I was out walking yesterday enjoying the flush of new grass that came from that rain storm 👍

**Pull request merged**
